name: 'Cinema Mode'
guid: '5fcefe1b-df1f-4596-ac57-f2f939c294c5'
version: '0.1.1.0'
targetAbi: '10.8.0.0'
framework: 'net6.0'
owner: 'CherryFloors'
overview: 'Enable Cinema Mode with local trailers and pre-rolls.'
description: >
  Enable Cinema Mode with local trailers and pre-rolls.
category: 'General'
artifacts:
- 'Jellyfin.Plugin.CinemaMode.dll'
changelog: >
  Initial Release
